# Generated by Django 4.1.7 on 2023-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_faculty_subjects_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='Faculty',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='Students',
            new_name='subjects',
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
